version: 2.1

parameters:
  tf_dir:
    type: string
    default: "infra"   # repo’daki TF klasör adın: "infra" veya "terraform"

jobs:
  build_package:
    docker:
      - image: cimg/node:22.21
    working_directory: ~/project
    steps:
      - checkout
      - run: npm ci
      - run: node build.mjs
      - run: zip -j lambda.zip dist/index.cjs
      - run: |
          echo "Repo root:"
          ls -la
          echo "TF dir listing:"
          ls -la "<< pipeline.parameters.tf_dir >>" || echo "No TF dir found"
      - persist_to_workspace:
          root: .
          paths:
            - lambda.zip
            - << pipeline.parameters.tf_dir >>

  terraform_plan:
    docker:
      - image: hashicorp/terraform:1.13
    working_directory: ~/project
    environment:
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: |
          echo "After attach, repo root:" && ls -la
          echo "TF dir:" && ls -la "<< pipeline.parameters.tf_dir >>"
      - run:
          name: Terraform Init
          command: |
            cd "<< pipeline.parameters.tf_dir >>" && terraform init -input=false
      - run:
          name: Terraform Validate (fmt + validate)
          command: |
            cd "<< pipeline.parameters.tf_dir >>" && terraform fmt -check
            cd "<< pipeline.parameters.tf_dir >>" && terraform validate
      - run:
          name: Terraform Plan (save as binary and human-readable)
          command: |
            cd "<< pipeline.parameters.tf_dir >>" && terraform plan -input=false -out tfplan
            cd "<< pipeline.parameters.tf_dir >>" && terraform show -no-color tfplan > plan.txt
            echo "---- Terraform Plan (excerpt) ----"
            head -n 200 "<< pipeline.parameters.tf_dir >>/plan.txt"
      - store_artifacts:
          path: << pipeline.parameters.tf_dir >>/plan.txt
          destination: plan.txt
      - store_artifacts:
          path: << pipeline.parameters.tf_dir >>/tfplan
          destination: tfplan
      - persist_to_workspace:
          root: .
          paths:
            - << pipeline.parameters.tf_dir >>/tfplan
            - << pipeline.parameters.tf_dir >>/.terraform
            - << pipeline.parameters.tf_dir >>/.terraform.lock.hcl
            - << pipeline.parameters.tf_dir >>/plan.txt

  terraform_apply:
    docker:
      - image: hashicorp/terraform:1.13
    working_directory: ~/project
    environment:
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Terraform Init (same backend/plugins)
          command: |
            cd "<< pipeline.parameters.tf_dir >>" && terraform init -input=false
#      - run:
#          name: Terraform Apply (using reviewed plan)
#          command: |
      #       cd "<< pipeline.parameters.tf_dir >>" && terraform apply -auto-approve tfplan

workflows:
  version: 2
  plan_review_apply:
    jobs:
      - build_package:
          filters:
            branches:
              only:
                - main
                - /feature\/.*/
      - terraform_plan:
          requires:
            - build_package
          context: [aws-deploy]
      - hold_for_approval:
          type: approval
          requires:
            - terraform_plan
          filters:
            branches:
              only: main
      - terraform_apply:
          requires:
            - hold_for_approval
          context: [aws-deploy]