version: 2.1

orbs:
  node: circleci/node@7.2.1

jobs:
  build_package:
    docker:
      - image: cimg/node:22.21
    working_directory: ~/project
    steps:
      - checkout
      - run: npm ci
      - run: node build.mjs
      - run: zip -j lambda.zip dist/index.cjs
      - persist_to_workspace:
          root: .
          paths:
            - lambda.zip
            - infra

  terraform_plan:
    docker:
      - image: hashicorp/terraform:1.13
    working_directory: ~/project
    environment:
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Terraform Init
          command: |
            cd infra && terraform init -input=false
      - run:
          name: Terraform Validate (fmt + validate)
          command: |
            cd infra && terraform fmt -check
            cd infra && terraform validate
      - run:
          name: Terraform Plan (save as binary and human-readable)
          command: |
            cd infra && terraform plan -input=false -out tfplan
            cd infra && terraform show -no-color tfplan > plan.txt
            echo "---- Terraform Plan (excerpt) ----"
            head -n 200 infra/plan.txt
      - store_artifacts:
          path: infra/plan.txt
          destination: plan.txt
      - store_artifacts:
          path: infra/tfplan
          destination: tfplan
      - persist_to_workspace:
          root: .
          paths:
            - infra/tfplan
            - infra/.terraform
            - infra/.terraform.lock.hcl
            - infra/plan.txt

  terraform_apply:
    docker:
      - image: hashicorp/terraform:1.13
    working_directory: ~/project
    environment:
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Terraform Init (same backend/plugins)
          command: |
            cd infra && terraform init -input=false
#      - run:
#          name: Terraform Apply (using reviewed plan)
#          command: |
#            cd infra && terraform apply -auto-approve tfplan

workflows:
  version: 2
  plan_review_apply:
    jobs:
      - build_package:
          filters:
            branches:
              only:
                - main
                - /feature\/.*/
      - terraform_plan:
          requires:
            - build_package
          context: [aws-deploy]
      - hold_for_approval:
          type: approval
          requires:
            - terraform_plan
          filters:
            branches:
              only: main
      - terraform_apply:
          requires:
            - hold_for_approval
          context: [aws-deploy]